# Generated by Django 2.2.7 on 2019-11-23 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reports',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
